### ISSUE TITLE
[Request]: Add points manual

### ISSUE THREAD

**Issue by Z3R0-CDS** [Axera-Digital/AxeraBO3#1]
Would be great title says it all.
Btw love the tool so far.

**Comment by SoniC-1337** [comment]
By this, do you mean you enter a custom amount or a button to increase by a set amount?

**Comment by Z3R0-CDS** [comment]
Both are great but a Button for increase sounds a bit better. But if the other one is more easy to add it would be fine too.

**Comment by Noodle-1337** [comment]
This can be added today!

**Comment by Z3R0-CDS** [comment]
Nice! While i got you here is it possible to rig the box for random guns? Or possible to give my self a gun and then packapunsh the weapon? 
And a explanation for the Weapon Cycle would be nice ^^
If you want I can send more I do have a few ideas xD

**Comment by Z3R0-CDS** [comment]
Still there?

**Comment by Noodle-1337** [comment]
Yup sorry been quite bust lately. I should have time tonight to work out some fixes and add this feature in. There will still be a checkbox for unlimited points. I'll just be adding an int input box so user can manually pick desired points.

**Comment by Z3R0-CDS** [comment]
Sounds great thanks

**Comment by Noodle-1337** [comment]
Set Custom Points have been added for Host. Issue resolved.
