### ISSUE TITLE
ESP + Zombie Counter not working

### ISSUE THREAD

**Issue by i-have-two-moms** [Axera-Digital/AxeraBO3#3]
I can't get the Zombie Counter and ESP to work while playing a Solo Game. Playing the game in offline mode seems to work fine, but as soon as I play a Solo Game while being online the ESP doesn't seem to show up no matter what I do.

Zombie Counter seems to be broken for me in both Online and Offline.

**Comment by Noodle-1337** [comment]
I will look into this at some point. I never tested it in solos so I'll have to see what the issue is.

**Comment by Noodle-1337** [comment]
Both issues resolved.
