### ISSUE TITLE
Weapon cycle and custom points

### ISSUE THREAD

**Issue by Z3R0-CDS** [Axera-Digital/AxeraBO3#4]
What is Weapon cycle?
And if you set it to -1 insta crash maybe disable the possibility to do that.

**Comment by Z3R0-CDS** [comment]
Few more things
Customs points:
   - Can not "disable" it
   - Would prefer to add/remove a custom ammount once not set it to a fixed ammount

**Comment by Noodle-1337** [comment]
> What is Weapon cycle? And if you set it to -1 insta crash maybe disable the possibility to do that.

- Weapon Cycle Crashing

This project is open source, you fork it and edit it to fix any issues that are present, and then push the merge so I can see the changes and accept it accordingly.

Yes having a check in place would stop the crashing from happening, I just didn't think anyone would enter a negative int value. That being said you can make a list yourself testing which weapons are assigned to which int value ( ex. 4 = AK ). They are specific to each map to my knowledge.

- Custom Points Sticking

This issue can be fixed fairly easily by adding another bool to track whether the points have been written to or not. Thus not writing the same point value over and over.
